export const ENABLE_SETTINGS = "ENABLE_SETTINGS";
export const DISABLE_SETTINGS = "DISABLE_SETTINGS";
export const SET_ACTIVE_TINT_COLOR = "SET_ACTIVE_TINT_COLOR";
export const GET_ACTIVE_TINT_COLOR = "GET_ACTIVE_TINT_COLOR";
export const SET_INACTIVE_TINT_COLOR = "SET_INACTIVE_TINT_COLOR";
export const GET_INACTIVE_TINT_COLOR = "GET_INACTIVE_TINT_COLOR";

export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const SAVE_SETTINGS_SUCCESS = "SAVE_SETTINGS_SUCCESS";
export const SAVE_SETTINGS_FAILURE = "SAVE_SETTINGS_FAILURE";

export const GET_SETTINGS = "GET_SETTINGS";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";
